spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-mysql:22221/mydb?useSSL=false
    username: nb_user
    password: nb_user
  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
          #dialect (??) DBMS?? ???? SQL? ??? ??? ?? SQL? ????? ?????.
          dialect : org.hibernate.dialect.MySQL5InnoDBDialect
